### ISSUE TITLE
Can't find the links for Gamble list

### ISSUE THREAD

**Issue by Atavic** [AdroitAdorKhan/Energized#31]
By looking at the first Package: **Energized** 
I see these sources listed: *Gamble, Drugs & Alcohol*.
I'd like to view the lists before using them... but I can't find their Urls or Raw links. 

Am I missing something?

**Comment by AdroitAdorKhan** [comment]
Hey @Atavic! Yea, those were added, but I couldn't find any exact link to keep them updated. So first, I needed to create source to keep them updated, that's why, they are kept away for the time being. 

You can check here - https://github.com/EnergizedProtection/EnergizedTools/tree/master/Converter/Hosts that, I have been creating those lists, to ensure they are updated. Once they are stable enough again, I will add them once again. 

Hope I have cleared things! :)
Feel free to ask, if you need anything more to know. :)

You can join our Telegram Group too!

**Comment by Atavic** [comment]
Maybe [this one](https://dsi.ut-capitole.fr/blacklists/index_en.php):

>Sites relative to drugs.
>Gambling and games sites, casino, etc.

**Comment by Atavic** [comment]
OK, I see shallagamble there.

Maybe [this info](https://dsi.ut-capitole.fr/blacklists/index_en.php) may be useful:

>Sites relative to drugs.
>Gambling and games sites, casino, etc.

**Comment by AdroitAdorKhan** [comment]
Great! Thanks!

I have already setup Shallalist Hosts. It will take bit more time to implement once again.

And, I will check your source, if i find anything more, I will make sure to add them.

**Comment by Atavic** [comment]
I don't know how fresh are those lists.

**Comment by AdroitAdorKhan** [comment]
That's why, I have added just few of them. I have added malware to Energized Hosts Converter, hope, I will be able to get daily fresh updates! :grin:

**Comment by AdroitAdorKhan** [comment]
Well, FYI, Ultimate Hosts Blacklists is also using Shalla's Sources, and I will check again, if false calls/inactive domains are there, I will consider removing them for good!

**Comment by AdroitAdorKhan** [comment]
I was planning to remove Shalla's all other sources, except Malware list, but as they are updated on regular basis, I thought about giving them a try! Let's see, if they are good enough to use in Energized! :zap:
